# ./bazelisk.sh query 'tests(//sw/device/...) except attr("tags", "skip_in_ci|manual|broken|sim|silicon", //sw/device/...)' | grep '/rom/' | grep 'instrumented_rom'
INS_ROM_TESTS=(
# PASSED
//sw/device/tests:uart_smoketest_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/retention_ram:rom_e2e_ret_ram_keep_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sram:sram_readback_default_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_a_flash_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_b_flash_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_a_flash_a_bad_addr_trans_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_v_flash_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_v_flash_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_bad_identifier_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_bad_identifier_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_end_unaligned_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_end_unaligned_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_in_manifest_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_in_manifest_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_outside_image_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_outside_image_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_start_unaligned_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_code_start_unaligned_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_empty_code_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_empty_code_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_entry_at_code_end_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_entry_at_code_end_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_entry_before_code_start_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_entry_before_code_start_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_entry_unaligned_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_entry_unaligned_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_resizable_rom_ext_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_resizable_rom_ext_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_rollback_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_rollback_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_too_large_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_too_large_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_too_small_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_bad_manifest:boot_policy_bad_manifest_rma_too_small_b_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/boot_policy_newer:boot_policy_newer_rma_a_0_b_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_newer:boot_policy_newer_rma_a_0_b_1_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_newer:boot_policy_newer_rma_a_1_b_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_newer:boot_policy_newer_rma_a_1_b_1_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_rollback:boot_policy_rollback_rma_a_0_b_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_rollback:boot_policy_rollback_rma_a_0_b_1_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_rollback:boot_policy_rollback_rma_a_1_b_1_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_rollback:boot_policy_rollback_rma_a_2_b_0_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_ecdsa_blank_rma_fake_ecdsa_prod_key_0_fake_spx_prod_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_ecdsa_blank_rma_fake_ecdsa_test_key_0_fake_spx_test_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_ecdsa_blank_rma_fake_ecdsa_dev_key_0_fake_spx_dev_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_ecdsa_revoked_rma_fake_ecdsa_dev_key_0_fake_spx_dev_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_ecdsa_revoked_rma_fake_ecdsa_prod_key_0_fake_spx_prod_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_ecdsa_revoked_rma_fake_ecdsa_test_key_0_fake_spx_test_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_blank_rma_fake_ecdsa_dev_key_0_fake_spx_dev_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_blank_rma_fake_ecdsa_prod_key_0_fake_spx_prod_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_blank_rma_fake_ecdsa_test_key_0_fake_spx_test_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_revoked_rma_fake_ecdsa_dev_key_0_fake_spx_dev_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_revoked_rma_fake_ecdsa_prod_key_0_fake_spx_prod_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_revoked_rma_fake_ecdsa_test_key_0_fake_spx_test_key_0_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e:rom_e2e_flash_ctrl_init_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reason_check_disabled_no_fault_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reason_check_disabled_with_fault_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reason_check_enabled_no_fault_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reason_check_uninitialized_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reasons_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/retention_ram:rom_e2e_ret_ram_init_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/rom_ext_upgrade_interrupt:rom_ext_upgrade_interrupt_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_watchdog:shutdown_watchdog_rma_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_watchdog:shutdown_watchdog_rma_200000_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sram:sram_readback_enabled_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reason_check_enabled_with_fault_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_all_constraints_mf_lc_dev_bs_lc_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_all_constraints_mf_lc_prod_bs_lc_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_all_constraints_mf_lc_prod_end_bs_lc_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_all_constraints_mf_lc_rma_bs_lc_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_all_constraints_mf_lc_test_bs_lc_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_device_id_family_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_device_id_family_no_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_device_id_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_device_id_no_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_invalid_unselected_device_id_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_invalid_unselected_life_cycle_state_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_invalid_unselected_manuf_state_creator_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_invalid_unselected_manuf_state_owner_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_lc_state_rma_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_lc_state_rma_no_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_manuf_state_creator_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_manuf_state_creator_no_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_manuf_state_owner_match_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_usage_constraints:sigverify_usage_constraint_manuf_state_owner_no_match_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_ecdsa_dev_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_ecdsa_prod_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_ecdsa_test_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_spx_dev_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_spx_prod_key_0_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_spx_test_key_0_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/shutdown_alert:alert_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_alert:shutdown_alert_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_output:shutdown_output_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_redact:e2e_shutdown_redact_rma_all_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_redact:e2e_shutdown_redact_rma_error_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_redact:e2e_shutdown_redact_rma_invalid_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_redact:e2e_shutdown_redact_rma_module_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/shutdown_redact:e2e_shutdown_redact_rma_none_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/rom_e2e_bootstrap_entry:e2e_bootstrap_entry_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e:rom_ext_upgrade_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e:sigverify_key_auth_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e:rom_e2e_shutdown_exception_c_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e:rom_e2e_smoke_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e:rom_e2e_static_critical_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_data_recovery:boot_data_recovery_rma_nodefault_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/boot_policy_big_image:boot_policy_big_image_rma_bigger_than_64k_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/epmp_init:epmp_init_otp_rma_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/keymgr:rom_e2e_keymgr_init_otp_invalid_meas_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/keymgr:rom_e2e_keymgr_init_otp_meas_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/keymgr:rom_e2e_keymgr_init_otp_no_meas_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_a_bad_b_bad_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_a_bad_b_good_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_valid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_valid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_valid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_hash_valid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_length_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_length_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_length_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_length_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_start_offset_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_start_offset_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_start_offset_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_disabled_start_offset_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_valid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_valid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_valid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_empty_hash_valid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_valid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_valid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_valid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_valid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_length_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_length_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_length_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_length_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_start_offset_invalid_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_start_offset_invalid_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_start_offset_invalid_virtual_a_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_start_offset_invalid_virtual_b_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_invalid_ok_when_disabled_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/watchdog:watchdog_disable_rma_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/watchdog:watchdog_enable_rma_fpga_cw340_instrumented_rom

//sw/device/silicon_creator/rom/e2e/clkmgr:jitter_disabled_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/clkmgr:jitter_enabled_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/rstmgr:cpu_info_disabled_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/rstmgr:cpu_info_enabled_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/rstmgr:alert_info_disabled_test_fpga_cw340_instrumented_rom
//sw/device/silicon_creator/rom/e2e/rstmgr:alert_info_enabled_test_fpga_cw340_instrumented_rom


# exec env (?)
#//sw/device/silicon_creator/rom/e2e/ate:ate_smoketest_fpga_cw340_instrumented_rom

# only on cw310
# //sw/device/silicon_creator/rom/e2e:rom_e2e_c_init_fpga_cw340_instrumented_rom


# Failed to program bitstream
# //sw/device/silicon_creator/rom/e2e:rom_e2e_default_otp_bootup_fpga_cw340_instrumented_rom
# //sw/device/silicon_creator/rom/e2e/boot_policy_valid:boot_policy_valid_rma_a_bad_b_bad_fpga_cw340_instrumented_rom
# //sw/device/silicon_creator/rom/e2e/boot_policy_valid:boot_policy_valid_rma_a_bad_b_good_fpga_cw340_instrumented_rom
# //sw/device/silicon_creator/rom/e2e/boot_policy_valid:boot_policy_valid_rma_a_good_b_bad_fpga_cw340_instrumented_rom
# //sw/device/silicon_creator/rom/e2e/boot_policy_valid:boot_policy_valid_rma_a_good_b_good_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_spx:sigverify_spx_prehashed_test_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_spx:sigverify_spx_rma_disabled_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_spx:sigverify_spx_rma_enabled_true_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_spx:sigverify_spx_rma_enabled_zero_fpga_cw340_instrumented_rom

# FAILED TIMEOUT - invalid BFV crash expectation after instrumented
# RomExt should idealy reject execution at wrong slot.
# //sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_a_flash_b_fpga_cw340_instrumented_rom
# //sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_b_flash_a_fpga_cw340_instrumented_rom

## FAILED TIMEOUT - flash ecc
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_code_first_word_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_code_end_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_code_start_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_ecdsa_public_key_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_ecdsa_signature_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_entry_point_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_extension_spx_public_key_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_extension_spx_signature_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_identifier_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_length_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_manifest_version_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_security_version_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_signed_region_end_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_manifest_usage_constraints_selector_bits_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_code_first_word_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_code_end_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_code_start_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_ecdsa_public_key_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_ecdsa_signature_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_entry_point_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_extension_spx_public_key_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_extension_spx_signature_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_identifier_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_length_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_manifest_version_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_security_version_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_signed_region_end_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_usage_constraints_selector_bits_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:flash_exc_handler_disabled_test_fpga_cw340_instrumented_rom

# ePMP is different in coverage mode.
#//sw/device/silicon_creator/rom/e2e/chip_specific_startup:e2e_chip_specific_startup_rma_fpga_cw340_instrumented_rom

# No load bitstream
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_asm_interrupt_handler_otp_test_unlocked0_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_debug_test_otp_dev_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_debug_test_otp_prod_end_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_debug_test_otp_prod_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_debug_test_otp_rma_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_debug_test_otp_test_unlocked0_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_shutdown_execution_asm_dev_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_shutdown_execution_asm_rma_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_shutdown_execution_asm_test_unlocked0_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:sram_program_fpga_cw310_test_otp_dev_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:sram_program_fpga_cw310_test_otp_rma_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:sram_program_fpga_cw310_test_otp_test_unlocked0_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/bootstrap:e2e_bootstrap_disabled_fpga_cw340_instrumented_rom

# FAILED TO BUILD
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_asm_interrupt_handler_otp_dev_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/jtag_inject:openocd_asm_interrupt_handler_otp_rma_fpga_cw340_instrumented_rom

# jtag
#//sw/device/silicon_creator/rom/e2e/bootstrap:e2e_bootstrap_rma_fpga_cw340_instrumented_rom


# firmware is empty???
#//sw/device/silicon_creator/rom/e2e/sigverify_always:sigverify_always_rma_a_bad_b_bad_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_always:sigverify_always_rma_a_bad_b_nothing_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_always:sigverify_always_rma_a_nothing_b_bad_fpga_cw340_instrumented_rom
#//sw/device/silicon_creator/rom/e2e/sigverify_always:sigverify_always_rma_a_nothing_b_nothing_fpga_cw340_instrumented_rom
)
