#!/bin/bash
set -euo pipefail

COVERAGE_OUTPUT_DIR="/tmp/${USER}/all_coverage/"

BASELINES=(
    "//sw/device/silicon_creator/rom_ext:rom_ext_prod_dice_cwt_spidfu_baseline_coverage"
    "//sw/device/silicon_creator/rom_ext:rom_ext_dice_x509_slot_virtual_baseline_coverage"
    "//sw/device/silicon_creator/rom_ext/imm_section:main_binaries_dice_cwt_slot_virtual_baseline_coverage"
    "//sw/device/silicon_creator/rom_ext/imm_section:main_binaries_dice_x509_slot_virtual_baseline_coverage"
    "//sw/device/silicon_creator/rom:instrumented_mask_rom_baseline_coverage"
)

TARGETS=(
)

# ./bazelisk.sh query 'tests(//sw/device/...) except attr("tags", "skip_in_ci|manual|broken|sim|silicon", //sw/device/...)'
TEST_ROM_TESTS=(
//sw/device/lib/testing/test_rom:test_rom_test_fpga_cw310_test_rom
//sw/device/tests:otp_ctrl_descrambling_test_fpga_cw310_test_rom
//sw/device/tests/crypto:rsa_3072_verify_functest_wycheproof_fpga_cw310_test_rom

# Report regex
# //sw/device/tests:status_report_test_fpga_cw310_test_rom
# //sw/device/tests:status_report_overflow_test_fpga_cw310_test_rom

# CHECK-fail: Mismatch between the expected digest and one generated by `scramble_image.py`.
# //sw/device/tests:kmac_app_rom_test_fpga_cw310_test_rom_fpga_cw310_test_rom

# Failed: cryptotest Quit command not found
# //sw/device/silicon_creator/lib/sigverify/sigverify_tests:sigverify_cryptotest_fpga_cw310_test_rom
)



UNIT_TESTS=(
//sw/device/lib/ujson:example_test
//sw/device/lib/ujson:ujson_test
//sw/device/lib/base:crc32_unittest
//sw/device/lib/base:hardened_memory_unittest
//sw/device/lib/base:hardened_unittest
//sw/device/lib/base:math_unittest
//sw/device/lib/base:memory_unittest
//sw/device/lib/base:mmio_unittest
//sw/device/lib/base:mock_csr_unittest
//sw/device/lib/base:status_report_unittest
//sw/device/lib/base:status_unittest
//sw/device/lib/crypto/impl:key_transport_unittest
//sw/device/lib/crypto/impl:status_debug_unittest
//sw/device/lib/crypto/impl:status_unittest
//sw/device/lib/crypto/impl/aes_gcm:ghash_unittest
//sw/device/lib/dif:adc_ctrl_unittest
//sw/device/lib/dif:aes_unittest
//sw/device/lib/dif:alert_handler_unittest
//sw/device/lib/dif:aon_timer_unittest
//sw/device/lib/dif:clkmgr_unittest
//sw/device/lib/dif:csrng_unittest
//sw/device/lib/dif:edn_unittest
//sw/device/lib/dif:entropy_src_unittest
//sw/device/lib/dif:flash_ctrl_unittest
//sw/device/lib/dif:gpio_unittest
//sw/device/lib/dif:hmac_unittest
//sw/device/lib/dif:i2c_unittest
//sw/device/lib/dif:keymgr_unittest
//sw/device/lib/dif:kmac_unittest
//sw/device/lib/dif:lc_ctrl_unittest
//sw/device/lib/dif:otbn_unittest
//sw/device/lib/dif:otp_ctrl_unittest
//sw/device/lib/dif:pattgen_unittest
//sw/device/lib/dif:pinmux_unittest
//sw/device/lib/dif:pwm_unittest
//sw/device/lib/dif:pwrmgr_unittest
//sw/device/lib/dif:rom_ctrl_unittest
//sw/device/lib/dif:rstmgr_unittest
//sw/device/lib/dif:rv_core_ibex_unittest
//sw/device/lib/dif:rv_dm_unittest
//sw/device/lib/dif:rv_plic_unittest
//sw/device/lib/dif:rv_timer_unittest
//sw/device/lib/dif:sensor_ctrl_unittest
//sw/device/lib/dif:spi_device_unittest
//sw/device/lib/dif:spi_host_unittest
//sw/device/lib/dif:sram_ctrl_unittest
//sw/device/lib/dif:sysrst_ctrl_unittest
//sw/device/lib/dif:uart_unittest
//sw/device/lib/dif:usbdev_unittest
//sw/device/lib/runtime:print_unittest
//sw/device/lib/testing:hexstr_unittest
//sw/device/sca/lib:prng_unittest
//sw/device/silicon_creator/lib:boot_data_unittest
//sw/device/silicon_creator/lib:boot_log_unittest
//sw/device/silicon_creator/lib:dbg_print_unittest
//sw/device/silicon_creator/lib:epmp_unittest
//sw/device/silicon_creator/lib:error_unittest
//sw/device/silicon_creator/lib:manifest_unittest
//sw/device/silicon_creator/lib:shutdown_unittest
//sw/device/silicon_creator/lib/base:sec_mmio_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_empty_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_enter_rescue_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_header_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_min_bl0_sec_ver_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_next_boot_bl0_slot_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_ownership_activate_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_ownership_history_unittest
//sw/device/silicon_creator/lib/boot_svc:boot_svc_ownership_unlock_unittest
//sw/device/silicon_creator/lib/cert:asn1_unittest
//sw/device/silicon_creator/lib/cert:cdi_0_template_unittest
//sw/device/silicon_creator/lib/cert:cdi_1_template_unittest
//sw/device/silicon_creator/lib/cert:cert_unittest
//sw/device/silicon_creator/lib/cert:cwt_cose_key_template_unittest
//sw/device/silicon_creator/lib/cert:cwt_dice_chain_entry_input_template_unittest
//sw/device/silicon_creator/lib/cert:cwt_dice_chain_entry_payload_template_unittest
//sw/device/silicon_creator/lib/cert:cwt_dice_chain_entry_template_unittest
//sw/device/silicon_creator/lib/cert:example_template_unittest
//sw/device/silicon_creator/lib/cert:generic_template_unittest
//sw/device/silicon_creator/lib/cert:tpm_ek_template_unittest
//sw/device/silicon_creator/lib/cert:uds_template_unittest
//sw/device/silicon_creator/lib/drivers:alert_unittest
//sw/device/silicon_creator/lib/drivers:ast_unittest
//sw/device/silicon_creator/lib/drivers:epmp_unittest
//sw/device/silicon_creator/lib/drivers:flash_ctrl_unittest
//sw/device/silicon_creator/lib/drivers:hmac_unittest
//sw/device/silicon_creator/lib/drivers:ibex_unittest
//sw/device/silicon_creator/lib/drivers:keymgr_unittest
//sw/device/silicon_creator/lib/drivers:kmac_unittest
//sw/device/silicon_creator/lib/drivers:lifecycle_unittest
//sw/device/silicon_creator/lib/drivers:otbn_unittest
//sw/device/silicon_creator/lib/drivers:otp_unittest
//sw/device/silicon_creator/lib/drivers:pinmux_unittest
//sw/device/silicon_creator/lib/drivers:retention_sram_unittest
//sw/device/silicon_creator/lib/drivers:rnd_unittest
//sw/device/silicon_creator/lib/drivers:rstmgr_unittest
//sw/device/silicon_creator/lib/drivers:sensor_ctrl_unittest
//sw/device/silicon_creator/lib/drivers:spi_device_unittest
//sw/device/silicon_creator/lib/drivers:uart_unittest
//sw/device/silicon_creator/lib/drivers:watchdog_unittest
//sw/device/silicon_creator/lib/ownership:isfb_unittest
//sw/device/silicon_creator/lib/ownership:ownership_activate_unittest
//sw/device/silicon_creator/lib/ownership:ownership_unlock_unittest
//sw/device/silicon_creator/lib/sigverify:flash_exec_unittest
//sw/device/silicon_creator/lib/sigverify:mod_exp_ibex_unittest
//sw/device/silicon_creator/lib/sigverify/sphincsplus:address_unittest
//sw/device/silicon_creator/rom:boot_policy_unittest
//sw/device/silicon_creator/rom:bootstrap_unittest
//sw/device/silicon_creator/rom_ext:rom_ext_boot_policy_unittest
//sw/device/silicon_creator/lib/ownership:owner_block_unittest
//sw/device/lib/ujson/rust:roundtrip_test
//sw/device/silicon_creator/manuf/base:perso_tlv_data_unittest

# CE: variable-sized object may not be initialized
# //sw/device/lib/crypto/impl:keyblob_unittest

# target platform (@local_config_platform//:host) didn't satisfy
# //sw/device/silicon_creator/lib/sigverify:sigverify_unittest
)


CW310_FAKE_KEYS_TESTS=(
//sw/device/lib/crypto/drivers:keymgr_test_fpga_cw310_rom_with_fake_keys
//sw/device/silicon_creator/lib/drivers:keymgr_functest_fpga_cw310_rom_with_fake_keys
//sw/device/silicon_creator/lib/drivers:rnd_functest_fpga_cw310_rom_with_fake_keys
//sw/device/tests:aes_smoketest_fpga_cw310_rom_with_fake_keys
//sw/device/tests:flash_ctrl_clock_freqs_test_fpga_cw310_rom_with_fake_keys
//sw/device/tests:flash_ctrl_mem_protection_test_fpga_cw310_rom_with_fake_keys
//sw/device/tests:flash_ctrl_ops_test_fpga_cw310_rom_with_fake_keys
//sw/device/tests:flash_ctrl_test_fpga_cw310_rom_with_fake_keys
//sw/device/tests:kmac_app_rom_test_fpga_cw310_rom_with_fake_keys_fpga_cw310_rom_with_fake_keys
//sw/device/tests:rstmgr_alert_info_test_fpga_cw310_rom_with_fake_keys

# Freeze
# //sw/device/tests:alert_handler_reverse_ping_in_deep_sleep_test_fpga_cw310_rom_with_fake_keys

# Prebuilt?
//sw/device/silicon_creator/rom_ext/e2e/dice_chain:variation_interop_cwt_first_test_fpga_cw310_rom_with_fake_keys
//sw/device/silicon_creator/rom_ext/e2e/dice_chain:variation_interop_x509_first_test_fpga_cw310_rom_with_fake_keys

# ???
# //sw/device/tests:alert_handler_lpg_sleep_mode_pings_test_fpga_cw310_rom_with_fake_keys
)

MANUF_TESTS=(
//sw/device/silicon_creator/manuf/lib:ast_program_functest_fpga_hyper310_rom_with_fake_keys
//sw/device/silicon_creator/manuf/lib:individualize_functest_fpga_cw340_sival
//sw/device/silicon_creator/manuf/lib:individualize_functest_fpga_hyper310_rom_with_fake_keys
//sw/device/silicon_creator/manuf/lib:individualize_sw_cfg_functest_fpga_cw340_rom_with_fake_keys
//sw/device/silicon_creator/manuf/lib:individualize_sw_cfg_functest_fpga_hyper310_rom_with_fake_keys

//sw/device/silicon_creator/manuf/tests:ujson_msg_padding_functest_fpga_cw340_sival
//sw/device/silicon_creator/manuf/tests:ujson_msg_padding_functest_fpga_hyper310_rom_with_fake_keys
//sw/device/silicon_creator/manuf/tests:ujson_msg_size_functest_fpga_cw340_sival
//sw/device/silicon_creator/manuf/tests:ujson_msg_size_functest_fpga_hyper310_rom_with_fake_keys

# //sw/device/silicon_creator/manuf/base:cp_provision_functest_fpga_cw340_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/base:cp_provision_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/lib:personalize_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked0_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked0_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked1_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked1_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked2_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked2_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked3_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked3_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked4_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked4_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked5_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked5_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked6_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked6_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked7_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_ast_test_execution_test_unlocked7_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked0_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked0_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked0_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked0_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked1_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked1_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked1_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked1_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked2_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked2_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked2_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked2_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked3_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked3_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked3_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked3_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked4_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked4_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked4_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked4_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked5_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked5_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked5_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked5_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked6_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked6_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked6_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked6_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked7_to_prod_end_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked7_to_prod_end_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked7_to_prod_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_device_info_flash_wr_test_unlocked7_to_prod_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_test_lock_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_test_lock_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_unlock_raw_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_unlock_raw_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_volatile_unlock_raw_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked0_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked0_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked1_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked1_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked2_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked2_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked3_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked3_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked4_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked4_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked5_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked5_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked6_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked6_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked7_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_cp_yield_test_functest_test_unlocked7_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_dev_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_dev_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_prod_end_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_prod_end_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_prod_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_prod_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_rma_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_rma_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked0_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked0_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked1_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked1_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked2_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked2_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked3_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked3_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked4_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked4_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked5_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked5_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked6_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_locked6_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked0_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked0_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked1_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked1_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked2_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked2_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked3_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked3_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked4_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked4_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked5_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked5_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked6_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked6_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked7_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_scrap_functest_test_unlocked7_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked0_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked0_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked1_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked1_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked2_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked2_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked3_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked3_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked4_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked4_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked5_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked5_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked6_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked6_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked7_functest_fpga_cw340_sival
# //sw/device/silicon_creator/manuf/tests:manuf_sram_program_crc_test_unlocked7_functest_fpga_hyper310_rom_with_fake_keys
# //sw/device/silicon_creator/manuf/tests:otp_ctrl_functest_fpga_hyper310_rom_with_fake_keys
)

CRYPTO_TESTS=(
//sw/device/tests/crypto/cryptotest:aes_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:cshake_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:drbg_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:ecdh_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:ecdsa_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:hmac_sha256_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:hmac_sha384_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:hmac_sha512_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:kmac_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha256_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha384_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha3_224_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha3_256_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha3_384_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha3_512_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sha512_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:shake128_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:shake256_kat_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto/cryptotest:sphincsplus_kat_fpga_cw310_sival_rom_ext
)

CW310_SIVAL_ROMEXT_TESTS=(
//sw/device/lib/base:crc32_functest_fpga_cw310_sival_rom_ext
//sw/device/lib/base:hardened_functest_fpga_cw310_sival_rom_ext
//sw/device/lib/crypto/drivers:aes_test_fpga_cw310_sival_rom_ext
//sw/device/lib/crypto/drivers:entropy_test_fpga_cw310_sival_rom_ext
//sw/device/lib/testing/test_framework:ottf_flow_control_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib:irq_asm_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:alert_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:kmac_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:retention_sram_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:rstmgr_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:uart_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:watchdog_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify:ecdsa_p256_verify_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify:mod_exp_ibex_functest_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify:rsa_verify_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify:sigverify_dynamic_functest_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/tests:aes_entropy_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aes_force_prng_reseed_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aes_masking_off_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aes_prng_reseed_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aes_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:aes_stall_test_fpga_cw310_sival_rom_ext
//sw/device/tests:alert_handler_escalation_test_fpga_cw310_sival_rom_ext
//sw/device/tests:alert_handler_lpg_clkoff_test_fpga_cw310_sival_rom_ext
//sw/device/tests:alert_handler_lpg_reset_toggle_test_fpga_cw310_sival_rom_ext
//sw/device/tests:alert_handler_ping_ok_test_fpga_cw310_sival_rom_ext
//sw/device/tests:alert_handler_ping_timeout_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aon_timer_irq_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aon_timer_sleep_wdog_sleep_pause_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aon_timer_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:aon_timer_wdog_bite_reset_test_fpga_cw310_sival_rom_ext
//sw/device/tests:aon_timer_wdog_lc_escalate_test_fpga_cw310_sival_rom_ext
//sw/device/tests:ast_clk_outs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:chip_power_idle_load_test_fpga_cw310_sival_rom_ext
//sw/device/tests:chip_power_sleep_load_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_external_clk_src_for_sw_fast_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_jitter_frequency_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_jitter_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_off_aes_trans_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_off_hmac_trans_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_off_kmac_trans_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_off_otbn_trans_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_off_peri_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_reset_frequency_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_sleep_frequency_test_fpga_cw310_sival_rom_ext
//sw/device/tests:clkmgr_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:csrng_kat_test_fpga_cw310_sival_rom_ext
//sw/device/tests:csrng_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:edn_auto_mode_fpga_cw310_sival_rom_ext
//sw/device/tests:edn_boot_mode_fpga_cw310_sival_rom_ext
//sw/device/tests:edn_kat_fpga_cw310_sival_rom_ext
//sw/device/tests:edn_sw_mode_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_ast_rng_req_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_bypass_mode_health_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_csrng_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_edn_reqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_fw_observe_many_contiguous_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_fw_override_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_fw_ovr_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_kat_test_fpga_cw310_sival_rom_ext
//sw/device/tests:entropy_src_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:example_mem_ujcmd_test_fpga_cw310_sival_rom_ext
//sw/device/tests:example_sival_fpga_cw310_sival_rom_ext
//sw/device/tests:example_test_from_flash_fpga_cw310_sival_rom_ext
//sw/device/tests:flash_ctrl_idle_low_power_test_fpga_cw310_sival_rom_ext
//sw/device/tests:flash_ctrl_write_clear_test_fpga_cw310_sival_rom_ext
//sw/device/tests:hmac_enc_idle_test_fpga_cw310_sival_rom_ext
//sw/device/tests:hmac_enc_test_fpga_cw310_sival_rom_ext
//sw/device/tests:hmac_secure_wipe_test_fpga_cw310_sival_rom_ext
//sw/device/tests:hmac_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:keymgr_derive_attestation_test_fpga_cw310_sival_rom_ext
//sw/device/tests:keymgr_derive_sealing_test_fpga_cw310_sival_rom_ext
//sw/device/tests:keymgr_key_derivation_test_fpga_cw310_sival_rom_ext
//sw/device/tests:keymgr_sideload_aes_test_fpga_cw310_sival_rom_ext
//sw/device/tests:keymgr_sideload_kmac_test_fpga_cw310_sival_rom_ext
//sw/device/tests:keymgr_sideload_otbn_test_fpga_cw310_sival_rom_ext
//sw/device/tests:kmac_endianess_test_fpga_cw310_sival_rom_ext
//sw/device/tests:kmac_idle_test_fpga_cw310_sival_rom_ext
//sw/device/tests:kmac_kmac_key_sideload_test_fpga_cw310_sival_rom_ext
//sw/device/tests:kmac_mode_cshake_test_fpga_cw310_sival_rom_ext
//sw/device/tests:kmac_mode_kmac_test_fpga_cw310_sival_rom_ext
//sw/device/tests:kmac_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:lc_ctrl_otp_hw_cfg0_test_fpga_cw310_sival_rom_ext
//sw/device/tests:otbn_ecdsa_op_irq_test_fpga_cw310_sival_rom_ext
//sw/device/tests:otbn_irq_test_fpga_cw310_sival_rom_ext
//sw/device/tests:otbn_isa_test_fpga_cw310_sival_rom_ext
//sw/device/tests:otbn_randomness_test_fpga_cw310_sival_rom_ext
//sw/device/tests:otbn_rsa_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pattgen_ios_test_fpga_cw310_sival_rom_ext
//sw/device/tests:plic_sw_irq_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pmp_smoketest_napot_fpga_cw310_sival_rom_ext
//sw/device/tests:pmp_smoketest_tor_fpga_cw310_sival_rom_ext
//sw/device/tests:pwm_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_all_reset_reqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_deep_sleep_all_reset_reqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_deep_sleep_all_wake_ups_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_deep_sleep_por_reset_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_lowpower_cancel_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_normal_sleep_all_reset_reqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_normal_sleep_all_wake_ups_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_normal_sleep_por_reset_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_random_sleep_all_reset_reqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_random_sleep_all_wake_ups_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_sleep_disabled_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_sleep_wake_5_bug_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_usb_clk_disabled_when_active_test_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_usbdev_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:pwrmgr_wdog_reset_reqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:rstmgr_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:rstmgr_sw_req_test_fpga_cw310_sival_rom_ext
//sw/device/tests:rstmgr_sw_rst_ctrl_test_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_core_ibex_icache_invalidate_test_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_core_ibex_isa_test_prod_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_core_ibex_mem_test_prod_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_core_ibex_nmi_irq_test_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_core_ibex_rnd_test_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_plic_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_timer_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:rv_timer_systick_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sensor_ctrl_alert_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sensor_ctrl_wakeup_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sleep_pin_mio_dio_val_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sleep_pwm_pulses_test_fpga_cw310_sival_rom_ext
//sw/device/tests:spi_device_flash_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:spi_device_ottf_console_test_fpga_cw310_sival_rom_ext
//sw/device/tests:spi_device_sleep_test_fpga_cw310_sival_rom_ext
//sw/device/tests:spi_device_ujson_console_test_fpga_cw310_sival_rom_ext
//sw/device/tests:spi_host_config_test_fpga_cw310_sival_rom_ext
//sw/device/tests:spi_host_irq_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_execution_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_memset_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_readback_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_scrambled_access_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_sleep_sram_ret_contents_no_scramble_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_sleep_sram_ret_contents_scramble_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests:sram_ctrl_subword_access_test_fpga_cw310_sival_rom_ext
//sw/device/tests:sysrst_ctrl_ec_rst_l_test_fpga_cw310_sival_rom_ext
//sw/device/tests:uart_smoketest_fpga_cw310_sival_rom_ext
//sw/device/tests/autogen:alert_test_fpga_cw310_sival_rom_ext
//sw/device/tests/autogen:plic_all_irqs_test_0_fpga_cw310_sival_rom_ext
//sw/device/tests/autogen:plic_all_irqs_test_10_fpga_cw310_sival_rom_ext
//sw/device/tests/autogen:plic_all_irqs_test_20_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:aes_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:aes_gcm_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:aes_kwp_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:aes_kwp_kat_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:aes_kwp_sideload_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:aes_sideload_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:drbg_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdh_p256_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdh_p256_sideload_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdh_p384_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdh_p384_sideload_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdsa_p256_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdsa_p256_sideload_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdsa_p256_verify_functest_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdsa_p384_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:ecdsa_p384_sideload_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:hkdf_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:hmac_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:hmac_multistream_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:hmac_sha256_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:hmac_sha384_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:hmac_sha512_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:kdf_hmac_ctr_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:kdf_kmac_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:kmac_functest_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:kmac_sideload_functest_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_2048_encryption_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_2048_key_from_cofactor_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_2048_keygen_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_2048_signature_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_3072_encryption_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_3072_keygen_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_3072_signature_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_3072_verify_functest_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_4096_encryption_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:rsa_4096_signature_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:sha256_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:sha384_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:sha512_functest_fpga_cw310_sival_rom_ext
//sw/device/tests/crypto:symmetric_keygen_functest_fpga_cw310_sival_rom_ext

//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:fors_test_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:mgf1_test_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:thash_test_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_hardcoded_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat0_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat1_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat2_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat3_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat4_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat5_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat6_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat7_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat8_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_kat9_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify/sphincsplus/test:wots_test_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/sigverify:spx_verify_functest_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:hmac_functest_fpga_cw310_sival_rom_ext

//sw/device/tests:flash_ctrl_clock_freqs_test_fpga_cw310_sival_rom_ext
//sw/device/tests:flash_ctrl_ops_test_fpga_cw310_sival_rom_ext

//sw/device/tests:usbdev_config_host_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_deep_reset_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_deep_resume_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_iso_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_mem_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_mixed_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_pincfg_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_pullup_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_sleep_reset_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_sleep_resume_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_stream_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_toggle_restore_test_fpga_cw310_sival_rom_ext
//sw/device/silicon_creator/lib/drivers:usb_functest_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_aon_pullup_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_setuprx_test_fpga_cw310_sival_rom_ext
//sw/device/tests:usbdev_vbus_test_fpga_cw310_sival_rom_ext

# //sw/device/tests:crt_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:rv_core_ibex_isa_test_test_unlocked0_fpga_cw310_sival_rom_ext
# //sw/device/tests:rv_core_ibex_mem_test_test_unlocked0_fpga_cw310_sival_rom_ext

# Timeout
# //sw/device/tests:power_virus_systemtest_fpga_cw310_sival_rom_ext
# //sw/device/tests:uart_baud_rate_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:uart_loopback_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:uart_parity_break_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sigverify_parallel_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:csrng_edn_concurrency_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:example_concurrency_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:uart_tx_rx_test_fpga_cw310_sival_rom_ext
# //sw/device/tests/crypto:rsa_4096_keygen_functest_fpga_cw310_sival_rom_ext


# Failed
# //sw/device/tests:usbdev_deep_disconnect_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:usbdev_suspend_resume_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:gpio_intr_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:gpio_pinmux_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:otbn_smoketest_fpga_cw310_sival_rom_ext
# //sw/device/tests:sleep_pin_retention_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sleep_pin_wake_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sysrst_ctrl_in_irq_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sysrst_ctrl_inputs_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sysrst_ctrl_outputs_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sysrst_ctrl_reset_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:sysrst_ctrl_ulp_z3_wakeup_test_fpga_cw310_sival_rom_ext
# //sw/device/tests/crypto:kdf_kmac_sideload_functest_hardcoded_fpga_cw310_sival_rom_ext
# //sw/device/tests:rstmgr_cpu_info_test_fpga_cw310_sival_rom_ext
# //sw/device/silicon_creator/lib/sigverify:mod_exp_ibex_functest_wycheproof_fpga_cw310_sival_rom_ext
# //sw/device/silicon_creator/lib/sigverify:sigverify_dynamic_functest_wycheproof_fpga_cw310_sival_rom_ext
# //sw/device/tests:aes_idle_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:gpio_smoketest_fpga_cw310_sival_rom_ext
# //sw/device/tests:spi_host_smoketest_fpga_cw310_sival_rom_ext
# //sw/device/tests:spi_host_winbond_flash_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:flash_ctrl_test_fpga_cw310_sival_rom_ext
# //sw/device/tests:ottf_dual_console_test_fpga_cw310_sival_rom_ext


# Perftest
# //sw/device/lib/base:memory_perftest_fpga_cw310_sival_rom_ext
)

CW310_SIVAL_TESTS=(
//sw/device/silicon_creator/lib:boot_data_functest_fpga_cw310_sival
//sw/device/silicon_creator/lib:otbn_boot_services_functest_fpga_cw310_sival
//sw/device/tests:aes_smoketest_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_dev_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_dev_personalized_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_prod_end_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_prod_end_personalized_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_prod_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_prod_personalized_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_rma_fpga_cw310_sival
//sw/device/tests:flash_ctrl_info_access_lc_test_unlocked0_fpga_cw310_sival
//sw/device/tests:keymgr_sideload_otbn_simple_test_fpga_cw310_sival
//sw/device/tests:kmac_app_rom_test_fpga_cw310_sival_fpga_cw310_sival
//sw/device/tests:kmac_error_conditions_test_fpga_cw310_sival
//sw/device/tests:otp_ctrl_mem_access_test_fpga_cw310_sival
//sw/device/tests:otp_ctrl_smoketest_fpga_cw310_sival
//sw/device/tests:rv_core_ibex_address_translation_test_fpga_cw310_sival
//sw/device/tests:rv_dm_lc_disabled_tl_dev_fpga_cw310_sival
//sw/device/tests:rv_dm_lc_disabled_tl_prod_end_fpga_cw310_sival
//sw/device/tests:rv_dm_lc_disabled_tl_prod_fpga_cw310_sival
//sw/device/tests:rv_dm_lc_disabled_tl_rma_fpga_cw310_sival
//sw/device/tests:rv_dm_lc_disabled_tl_test_unlocked1_fpga_cw310_sival

# OpenOCD: runnable but empty coverage
# //sw/device/tests:rv_dm_lc_disabled_jtag_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_lc_disabled_jtag_prod_end_fpga_cw310_sival
# //sw/device/tests:rv_dm_lc_disabled_jtag_prod_fpga_cw310_sival
# //sw/device/tests:rv_dm_lc_disabled_jtag_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_lc_disabled_jtag_test_locked0_fpga_cw310_sival
# //sw/device/tests:rv_dm_lc_disabled_jtag_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_access_after_hw_reset_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_access_after_hw_reset_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_access_after_hw_reset_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_access_after_wakeup_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_access_after_wakeup_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_access_after_wakeup_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_control_status_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_control_status_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_control_status_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_csr_rw_dev_rv_dm_default_enabled_fpga_cw310_sival
# //sw/device/tests:rv_dm_csr_rw_dev_rv_dm_delayed_enabled_fpga_cw310_sival
# //sw/device/tests:rv_dm_csr_rw_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_csr_rw_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_dtm_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_dtm_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_dtm_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_tap_sel_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_tap_sel_prod_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_tap_sel_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_tap_sel_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_jtag_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_mem_access_dev_rv_dm_default_enabled_fpga_cw310_sival
# //sw/device/tests:rv_dm_mem_access_dev_rv_dm_delayed_enabled_fpga_cw310_sival
# //sw/device/tests:rv_dm_mem_access_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_mem_access_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_ndm_reset_req_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_ndm_reset_req_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_ndm_reset_req_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:rv_dm_ndm_reset_req_when_cpu_halted_dev_fpga_cw310_sival
# //sw/device/tests:rv_dm_ndm_reset_req_when_cpu_halted_rma_fpga_cw310_sival
# //sw/device/tests:rv_dm_ndm_reset_req_when_cpu_halted_test_unlocked1_fpga_cw310_sival
# //sw/device/tests:sram_ctrl_lc_escalation_test_fpga_cw310_sival

# Timeout
# //sw/device/tests:i2c_target_smbus_arp_test_fpga_cw310_sival

# Failed
# //sw/device/tests:i2c_host_override_test_fpga_cw310_sival
# //sw/device/tests:i2c_target_test_fpga_cw310_sival
)

IMM_TESTS=(
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_imm_section_virtual_a_fpga_hyper310_rom_ext

# ???
# //sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_romext_virtual_a_with_imm_romext_enabled_fpga_hyper310_rom_ext

# arch lib is not stripped
# //sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env:env_independent_dice_cwt_slot_a_test
# //sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env:env_independent_dice_cwt_slot_b_test
# //sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env:env_independent_dice_cwt_slot_virtual_test
# //sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env:env_independent_dice_x509_slot_a_test
# //sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env:env_independent_dice_x509_slot_b_test
# //sw/device/silicon_creator/rom_ext/imm_section/e2e/exec_env:env_independent_dice_x509_slot_virtual_test
)

HYPER310_ROMEXT_TESTS=(
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_bad_next_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_bad_primary_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_empty_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_next_aab_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_next_aba_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_primary_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_wakeup_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/handoff:fault_hardware_interrupt_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/handoff:fault_illegal_instruction_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/handoff:fault_load_access_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/handoff:fault_none_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/handoff:fault_store_access_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_activate_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_app_key_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_appkey_constraint_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_endorsee_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_locked_update_no_exec_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_locked_update_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_owner_block_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_unlock_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_error_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:fpga_owner_upgrade_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:good_appkey_constraint_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:locked_update_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_badlock_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_nodelock_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_noupdate_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_pq_downgrade_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_update_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_any_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_endorsed_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_enter_on_fail_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_enter_on_fail_xmodem_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_inactivity_timeout_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_too_big_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:bad_manifest_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_dev_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_prod_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_unauthorized_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_owner_slot_a_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_owner_slot_b_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_owner_virtual_a_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_owner_virtual_b_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_romext_slot_a_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_romext_slot_b_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_romext_virtual_a_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_romext_virtual_b_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_enter_rescue_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:next_slot_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:next_slot_xmodem_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:primary_slot_xmodem_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_slot_a_xmodem_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_slot_b_xmodem_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rate_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_min_sec_ver_a_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_min_sec_ver_b_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/attestation:print_certs_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_code_first_word_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_code_end_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_code_start_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_ecdsa_public_key_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_ecdsa_signature_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_entry_point_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_extension_spx_public_key_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_extension_spx_signature_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_identifier_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_length_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_manifest_version_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_security_version_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_signed_region_end_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_usage_constraints_selector_bits_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_code_first_word_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_code_end_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_code_start_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_ecdsa_public_key_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_ecdsa_signature_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_entry_point_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_extension_spx_public_key_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_extension_spx_signature_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_identifier_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_length_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_manifest_version_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_security_version_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_signed_region_end_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_usage_constraints_selector_bits_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:flash_exc_handler_disabled_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rom_ext_slot_a_update_slot_b_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rom_ext_slot_b_update_slot_a_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rom_ext_slot_a_update_slot_a_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rom_ext_slot_b_update_slot_b_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_dev_hybrid_spx_prehashed_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_prod_hybrid_spx_pure_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_permission_test_slot_bb_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_permission_test_slot_aa_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_permission_test_slot_ab_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_permission_test_slot_ba_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_ecdsa_to_pq_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_keymgr_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_pq_to_pq_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_slot_a_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_slot_b_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_pq_to_pq_update_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:rescue_limit_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:rescue_permission_test_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_bad_product_expr_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_bad_strike_mask_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_page_bad_erase_constraint_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_page_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_product_expr_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_unconstrained_test_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_get_boot_log_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_get_boot_log_xmodem_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_get_device_id_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_get_device_id_xmodem_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/secver:secver_write_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/verified_boot:isfb_boot_test_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/rescue/std_utils:xmodem_protocol_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:spidfu_restricted_commands_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:xmodem_restricted_commands_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/rescue:primary_slot_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_inactivity_timeout_preserved_reset_reason_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/rescue:next_slot_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:primary_slot_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_enter_on_fail_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_slot_a_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_slot_b_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_get_boot_log_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_get_device_id_usbdfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_disability_spidfu_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_disability_xmodem_fpga_hyper310_rom_ext

//sw/device/silicon_creator/rom_ext/e2e/ownership:invalid_key_alg_activate_request_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_ownership_key_alg_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_ownership_key_alg_with_detached_sig_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_spx_pure_to_spx_prehash_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_unlock_signature_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:unlock_with_owner_recovery_key_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/ownership:unlock_detached_sig_test_fpga_hyper310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/handoff:fault_return_boot_failed_fpga_hyper310_rom_ext

# FAILED
# //sw/device/silicon_creator/rom_ext/e2e/rescue/std_utils:usbdfu_protocol_fpga_hyper310_rom_ext

# Report regex
# //sw/device/silicon_creator/rom_ext/e2e/handoff:epmp_test_fpga_hyper310_rom_ext


# Timeout: the prebuilt protocol 0 uses an incompatible layout. (i.e. 64K boundary)
# //sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_firmware_protocol_0_fpga_hyper310_rom_ext
)

CW310_ROMEXT_TESTS=(
//sw/device/silicon_creator/rom_ext/e2e/dice_chain:no_refresh_dice_cwt_test_fpga_cw310_rom_ext
//sw/device/silicon_creator/rom_ext/e2e/dice_chain:no_refresh_dice_x509_test_fpga_cw310_rom_ext
//sw/device/silicon_owner/bare_metal:rom_ext_virtual_ottf_bl0_virtual_fpga_cw310_rom_ext
//sw/device/tests:aes_smoketest_fpga_cw310_rom_ext
//sw/device/tests/crypto:otcrypto_export_test_fpga_cw310_rom_ext
//sw/device/tests/crypto:otcrypto_hash_test_fpga_cw310_rom_ext
//sw/device/silicon_owner/bare_metal:rom_ext_virtual_bare_metal_virtual_boot_test_fpga_cw310_rom_ext
)

CW340_SIVAL_TESTS=(
//sw/device/tests:aes_interrupt_encryption_test_fpga_cw340_sival
//sw/device/tests:hmac_endianness_test_fpga_cw340_sival
//sw/device/tests:hmac_error_conditions_test_fpga_cw340_sival
//sw/device/tests:kmac_app_rom_test_fpga_cw340_sival_fpga_cw340_sival
//sw/device/tests:kmac_entropy_test_fpga_cw340_sival
//sw/device/tests:otbn_mem_scramble_test_fpga_cw340_sival
)

CW340_FAKE_KEYS_TESTS=(
//sw/device/tests:ottf_console_with_gpio_tx_indicator_test_fpga_cw340_rom_with_fake_keys
)

CW340_ROM_EXT_TESTS=(
//sw/device/silicon_creator/rom_ext/e2e/dice_chain:corrupted_digest_test_fpga_cw340_rom_ext
)

HYPER310_FAKE_KEYS_TESTS=(
//sw/device/tests:ottf_console_with_gpio_tx_indicator_test_fpga_hyper310_rom_with_fake_keys
)

PROVISIONING_TESTS=(
//sw/host/provisioning/orchestrator/tests:e2e_emulation_cw340_test
//sw/host/provisioning/orchestrator/tests:e2e_emulation_dice_cwt_cw340_test
//sw/host/provisioning/orchestrator/tests:e2e_emulation_tpm_cw340_test
)

UNSUPPORTED_TESTS=(
//sw/device/lib/base:global_mock_unittest
//sw/device/tests/penetrationtests:fi_crypto_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:fi_ibex_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:fi_lc_ctrl_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:fi_otbn_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:fi_otp_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:fi_rng_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:fi_rom_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_aes_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_edn_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_hmac_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_ibex_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_kmac_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_otbn_fpga_cw310_sival_rom_ext
//sw/device/tests/penetrationtests:sca_sha3_fpga_cw310_sival_rom_ext
//third_party/coremark/top_earlgrey:coremark_test_fpga_cw310_rom_with_fake_keys
//third_party/coremark/top_earlgrey:coremark_test_fpga_cw310_sival_rom_ext
//third_party/coremark/top_earlgrey:coremark_test_silicon_owner_sival_rom_ext
//third_party/coremark/top_earlgrey:coremark_test_sim_dv
//third_party/coremark/top_earlgrey:coremark_test_sim_qemu_rom_with_fake_keys
//third_party/coremark/top_earlgrey:coremark_test_sim_verilator
//sw/device/coverage/collect_cc_coverage:collect_cc_coverage_test
//sw/device/tests:coverage_test_fpga_cw340_sival_rom_ext
)

source ./rom_targets.sh
source ./targets_skip_in_ci.sh
source ./targets_useful_extra.sh

TEST_GROUPS=(
    "UNIT_TESTS"
    "TEST_ROM_TESTS"
    "CW310_FAKE_KEYS_TESTS"
    "MANUF_TESTS"
    "CRYPTO_TESTS"
    "CW310_SIVAL_ROMEXT_TESTS"
    "CW310_SIVAL_TESTS"
    "IMM_TESTS"
    "HYPER310_ROMEXT_TESTS"
    "CW310_ROMEXT_TESTS"
    "CW340_SIVAL_TESTS"
    "CW340_FAKE_KEYS_TESTS"
    "CW340_ROM_EXT_TESTS"
    "HYPER310_FAKE_KEYS_TESTS"
    "INS_ROM_TESTS"
    "PROVISIONING_TESTS"
    "USEFUL_EXTRA_TESTS"
    # "${EX_TEST_GROUPS[@]}"
)

_TARGETS=()
for test_group_name in "${TEST_GROUPS[@]}"; do
    _TARGETS+=( "${test_group[@]}" )
done

# TARGETS=_TARGETS

BAZEL_ARGS=(
    --test_output=streamed
    # --test_timeout=600
    --copt=-Wno-error
    --copt=-Wno-enum-constexpr-conversion
    # --cache_test_results=no
    --config=ot_coverage
    --local_test_jobs=1
    --notest_runner_fail_fast
    --keep_going
    # --jobs=1
    # --subcommands
)

source ./run_all_coverage_impl.sh
