#!/bin/bash
set -euo pipefail

COVERAGE_OUTPUT_DIR="/tmp/${USER}/all_coverage/"

BASELINES=(
    "//sw/device/silicon_creator/rom:instrumented_mask_rom_baseline_coverage"
)

TARGETS=(
    # //sw/device/lib/base:crc32_functest_fpga_cw310_sival_rom_ext
    # //sw/device/tests:uart_smoketest_fpga_cw340_test_rom
    # //sw/device/tests:uart_smoketest_fpga_cw340_rom_with_fake_keys
    # //sw/device/tests:uart_smoketest_fpga_cw340_rom_ext
    # //sw/device/tests:uart_smoketest_fpga_cw310_sival_rom_ext

    # //sw/device/lib/crypto/drivers:aes_test_fpga_cw310_rom_with_fake_keys
    # //sw/device/lib/base:crc32_unittest
    # //sw/device/tests/crypto/cryptotest:hmac_sha256_kat_fpga_cw340_test_rom
    # //sw/device/silicon_creator/rom_ext/e2e/dice_chain:no_refresh_dice_x509_test_fpga_cw340_rom_ext
    # //sw/device/tests:rv_core_ibex_isa_test_prod_fpga_cw310_rom_with_fake_keys

    # //sw/device/silicon_creator/manuf/base:cp_provision_functest_fpga_cw340_rom_with_fake_keys
    # //sw/device/tests:rv_core_ibex_epmp_test_functest_fpga_cw310_rom_with_fake_keys

# //sw/device/silicon_creator/rom_ext/e2e/dice_chain:variation_interop_cwt_first_test_fpga_cw310_rom_with_fake_keys

# //sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_imm_section_virtual_a_fpga_hyper310_rom_ext
# //sw/device/silicon_creator/rom:stack_utilization_test

)

# ./bazelisk.sh query 'tests(//sw/device/...) except attr("tags", "skip_in_ci|manual|broken|sim|silicon", //sw/device/...)'
TEST_ROM_TESTS=(
//sw/device/lib/testing/test_rom:test_rom_test_fpga_cw310_test_rom
//sw/device/tests:otp_ctrl_descrambling_test_fpga_cw310_test_rom
//sw/device/tests/crypto:rsa_3072_verify_functest_wycheproof_fpga_cw310_test_rom

# Report regex
# //sw/device/tests:status_report_test_fpga_cw310_test_rom
# //sw/device/tests:status_report_overflow_test_fpga_cw310_test_rom

# CHECK-fail: Mismatch between the expected digest and one generated by `scramble_image.py`.
# //sw/device/tests:kmac_app_rom_test_fpga_cw310_test_rom_fpga_cw310_test_rom

# Failed: cryptotest Quit command not found
# //sw/device/silicon_creator/lib/sigverify/sigverify_tests:sigverify_cryptotest_fpga_cw310_test_rom
)

source rom_targets.sh

TEST_GROUPS=(
    "INS_ROM_TESTS"
)

TARGETS+=(
    "${INS_ROM_TESTS[@]}"
)

BAZEL_ARGS=(
    --test_output=streamed
    # --test_timeout=600
    --copt=-Wno-error
    --copt=-Wno-enum-constexpr-conversion
    # --cache_test_results=no
    --config=ot_coverage
    --local_test_jobs=1
    --notest_runner_fail_fast
    --keep_going
    # --jobs=1
    # --subcommands
)

source ./run_all_coverage_impl.sh
