CW310_ROM_EXT_TESTS=(
  '//sw/device/silicon_creator/rom_ext/e2e/dice_chain:no_refresh_dice_cwt_test_fpga_cw310_rom_ext'
)

CW310_SIVAL_ROM_EXT_TESTS=(
  '//sw/device/silicon_creator/lib/sigverify:spx_verify_functest_fpga_cw310_sival_rom_ext'
  '//sw/device/tests/crypto:drbg_functest_fpga_cw310_sival_rom_ext'
  '//sw/device/tests:kmac_smoketest_fpga_cw310_sival_rom_ext'
  '//sw/device/tests:pwrmgr_normal_sleep_all_wake_ups_fpga_cw310_sival_rom_ext'
)

CW310_SIVAL_TESTS=(
  '//sw/device/silicon_creator/lib:boot_data_functest_fpga_cw310_sival'
  '//sw/device/silicon_creator/lib:otbn_boot_services_functest_fpga_cw310_sival'
)

CW340_INSTRUMENTED_ROM_TESTS=(
  '//sw/device/silicon_creator/rom/e2e/address_translation:rom_ext_a_flash_a_bad_addr_trans_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/boot_policy_newer:boot_policy_newer_test_unlocked0_a_1_b_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/boot_policy_rollback:boot_policy_rollback_prod_end_a_0_b_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/immutable_rom_ext_section:immutable_section_exec_enabled_hash_valid_virtual_b_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/keymgr:rom_e2e_keymgr_init_otp_meas_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/reset_reason:reset_reason_check_enabled_with_fault_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/retention_ram:rom_e2e_ret_ram_keep_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/rom_e2e_bootstrap_entry:e2e_bootstrap_entry_test_unlocked0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/shutdown_alert:shutdown_alert_dev_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_dev_fake_spx_test_key_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_prod_end_fake_spx_test_key_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_prod_fake_ecdsa_dev_key_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/sigverify_key_type:sigverify_key_type_rma_fake_spx_dev_key_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/sigverify_key_validity:sigverify_key_validity_spx_blank_test_unlocked0_fake_ecdsa_dev_key_0_fake_spx_dev_key_0_fpga_cw340_instrumented_rom'
  '//sw/device/silicon_creator/rom/e2e/watchdog:watchdog_disable_test_unlocked0_fpga_cw340_instrumented_rom'
)

CW340_ROM_EXT_TESTS=(
  '//sw/device/silicon_creator/rom_ext/e2e/verified_boot:position_romext_slot_a_fpga_cw340_rom_ext'
)

HYPER310_ROM_EXT_TESTS=(
  '//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_bad_next_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_empty_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/boot_svc:boot_svc_min_sec_ver_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_corrupt_b_valid_manifest_manifest_version_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:a_valid_b_corrupt_manifest_code_end_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/flash_ecc_error:flash_exc_handler_disabled_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/isfb:isfb_product_expr_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/ownership:bad_locked_update_no_exec_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_error_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/ownership:flash_permission_test_slot_ba_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_badlock_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/ownership:newversion_update_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/ownership:transfer_pq_to_pq_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/rescue:next_slot_spidfu_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_enter_on_fail_spidfu_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_inactivity_timeout_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rate_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/rescue:rescue_rom_ext_slot_a_update_slot_a_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/secver:secver_write_test_fpga_hyper310_rom_ext'
  '//sw/device/silicon_creator/rom_ext/e2e/verified_boot:key_dev_hybrid_spx_prehashed_fpga_hyper310_rom_ext'
)

UNIT_TESTS=(
  '//sw/device/lib/base:crc32_unittest'
  '//sw/device/lib/base:memory_unittest'
  '//sw/device/lib/crypto/impl:status_unittest'
  '//sw/device/silicon_creator/lib/boot_svc:boot_svc_header_unittest'
  '//sw/device/silicon_creator/lib/cert:cdi_1_template_unittest'
  '//sw/device/silicon_creator/lib/cert:generic_template_unittest'
  '//sw/device/silicon_creator/lib/drivers:alert_unittest'
  '//sw/device/silicon_creator/lib/drivers:ast_unittest'
  '//sw/device/silicon_creator/lib/drivers:flash_ctrl_unittest'
  '//sw/device/silicon_creator/lib/drivers:ibex_unittest'
  '//sw/device/silicon_creator/lib/drivers:keymgr_unittest'
  '//sw/device/silicon_creator/lib/drivers:kmac_unittest'
  '//sw/device/silicon_creator/lib/drivers:lifecycle_unittest'
  '//sw/device/silicon_creator/lib/drivers:otbn_unittest'
  '//sw/device/silicon_creator/lib/drivers:otp_unittest'
  '//sw/device/silicon_creator/lib/drivers:rnd_unittest'
  '//sw/device/silicon_creator/lib/drivers:spi_device_unittest'
  '//sw/device/silicon_creator/lib/drivers:watchdog_unittest'
  '//sw/device/silicon_creator/lib/ownership:isfb_unittest'
  '//sw/device/silicon_creator/lib/ownership:ownership_activate_unittest'
  '//sw/device/silicon_creator/lib/ownership:ownership_unlock_unittest'
  '//sw/device/silicon_creator/lib:boot_data_unittest'
  '//sw/device/silicon_creator/lib:boot_log_unittest'
  '//sw/device/silicon_creator/lib:dbg_print_unittest'
  '//sw/device/silicon_creator/lib:epmp_unittest'
  '//sw/device/silicon_creator/lib:manifest_unittest'
  '//sw/device/silicon_creator/rom:boot_policy_unittest'
  '//sw/device/silicon_creator/rom_ext:rom_ext_boot_policy_unittest'
)


TEST_GROUPS=(
  'EXTRA_TESTS'
  'CW310_ROM_EXT_TESTS'
  'CW310_SIVAL_ROM_EXT_TESTS'
  'CW310_SIVAL_TESTS'
  'CW340_INSTRUMENTED_ROM_TESTS'
  'CW340_ROM_EXT_TESTS'
  'HYPER310_ROM_EXT_TESTS'
  'UNIT_TESTS'
)
