# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

load("//rules/opentitan:rust.bzl", "cc_library_with_bindgen")

cc_library_with_bindgen(
    name = "main_lib",
    srcs = ["imm_rom_ext.c"],
    hdrs = ["imm_rom_ext.h"],
)
