
# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load(
    "//sw/device/silicon_creator/rom_ext/imm_section:utils.bzl",
    "create_imm_section_targets",
)

package(default_visibility = ["//visibility:public"])

create_imm_section_targets(
    name = "main_binaries_dice_x509_slot_virtual_silicon_creator",
    src = "main_binaries_dice_x509_slot_virtual_silicon_creator.bin",
)

create_imm_section_targets(
    name = "main_binaries_dice_cwt_slot_virtual_silicon_creator",
    src = "main_binaries_dice_cwt_slot_virtual_silicon_creator.bin",
)
